config/routes.rb
Rails.application.routes.draw do
  resources :payment_schedules

  devise_for :users, controllers: { registrations: 'registrations' }
  root 'welcome#index'

  get '/dashboard' => 'dashboard#index', as: :dashboard
  get "/prepare/:id" => "payments#preapprovalkey"
  get "/subs/:id" => "payments#subscription"
  get "/payonce/:id" => "payments#pay"

  get "/succeed" => "payments#succeed"
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/payment_schedule.rb
class PaymentSchedule < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :payment_schedules

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @creditors = current_user.payment_schedules
  end
end

app/controllers/payment_schedules_controller.rb
class PaymentSchedulesController < ApplicationController
  before_action :set_payment_schedule, only: [:show, :edit, :update, :destroy]

  # GET /payment_schedules
  # GET /payment_schedules.json
  def index
    @payment_schedules = PaymentSchedule.all
  end

  # GET /payment_schedules/1
  # GET /payment_schedules/1.json
  def show
  end

  # GET /payment_schedules/new
  def new
    @payment_schedule = PaymentSchedule.new
  end

  # GET /payment_schedules/1/edit
  def edit
  end

  # POST /payment_schedules
  # POST /payment_schedules.json
  def create
    @payment_schedule = PaymentSchedule.new(payment_schedule_params)

    respond_to do |format|
      if @payment_schedule.save
        format.html { redirect_to @payment_schedule, notice: 'Payment schedule was successfully created.' }
        format.json { render :show, status: :created, location: @payment_schedule }
      else
        format.html { render :new }
        format.json { render json: @payment_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_schedules/1
  # PATCH/PUT /payment_schedules/1.json
  def update
    respond_to do |format|
      if @payment_schedule.update(payment_schedule_params)
        format.html { redirect_to @payment_schedule, notice: 'Payment schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_schedule }
      else
        format.html { render :edit }
        format.json { render json: @payment_schedule.errors, status: :unprocessable_entity }
        
      end
    end
  end

  # DELETE /payment_schedules/1
  # DELETE /payment_schedules/1.json
  def destroy
    @payment_schedule.destroy
    respond_to do |format|
      format.html { redirect_to payment_schedules_url, notice: 'Payment schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_schedule
      @payment_schedule = PaymentSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_schedule_params
      params.require(:payment_schedule).permit(:account, :regularity, :start_date, :end_date, :amount, :name, :user_id)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  require 'date'
  require 'paypal-sdk-adaptivepayments'
  require 'rest_client'
  require "pp-adaptive"
  require 'json'

  def check_for_payments
    end
  def test
    result = PaymentSchedule.new
    result = result.pay(User.last, PaymentSchedule.last)
    render json: result
  end

  def pay
    payment = PaymentSchedule.find(params[:id])
    @api = PayPal::SDK::AdaptivePayments.new

    # Build request object
    @pay = @api.build_pay({
      :actionType => "PAY",
      :cancelUrl => "http://localhost:3000/samples/adaptive_payments/pay",
      :currencyCode => "MXN",
      :senderEmail => payment.user.email,
      :ipnNotificationUrl => "http://localhost:3000/samples/adaptive_payments/ipn_notify",
      :memo => "Nomina",
      :receiverList => {
        :receiver => [{
          :amount => payment.amount,
          :email => payment.account }] },
      :returnUrl => "http://localhost:3000/samples/adaptive_payments/pay" })

    # Make API call & get response
    @response = @api.pay(@pay)

    # Access response
    if @response.success? && @response.payment_exec_status != "ERROR"
      @response.payKey
      redirect_to @api.payment_url(@response)  # Url to complete payment
    else
      @response.error[0].message
      render json: @response
    end
    
  end

  def subscription
    #PA-2BS25581P84232213
    payment = PaymentSchedule.find(params[:id]);
    client = AdaptivePayments::Client.new(
      :user_id       => "dude_api1.hotmail.es",
      :password      => "WC89FAW4E6N5PEKA",
      :signature     => "AFcWxV21C7fd0v3bYYYRCpSSRl31ACwd6g7hhhBCeUn.ndSBp5HmqJIl",
      :app_id        => "APP-80W284485P519543T",
      :sandbox       => true
    )

    client.execute(:Pay,
      :preapproval_key => payment.pak,
      :action_type     => "PAY",
      :receiver_email  => payment.account,
      :receiver_amount => payment.amount,
      :currency_code   => "MXN",
      :memo => "Nomina",
      :cancel_url      => "https://lvh.me:3000/cancel",
      :return_url      => "https://lvh.me:3000/"
    ) do |response|

      if response.success?
        puts "Pay key: #{response.pay_key}"
        puts "Status: #{response.payment_exec_status}"
      else
        puts "#{response.ack_code}: #{response.error_message}"
      end
      @response = response
      @resJSON =  response.to_json
      render :succeed
    end
  end

  def preapprovalkey
    payment = PaymentSchedule.find(params[:id])

    client = AdaptivePayments::Client.new(
      :user_id       => "dude_api1.hotmail.es",
      :password      => "WC89FAW4E6N5PEKA",
      :signature     => "AFcWxV21C7fd0v3bYYYRCpSSRl31ACwd6g7hhhBCeUn.ndSBp5HmqJIl",
      :app_id        => "APP-80W284485P519543T",
      :sandbox       => true
    )

    client.execute(:Preapproval,
      :ending_date      => payment.end_date,
      :starting_date    => payment.start_date,
      :max_total_amount => BigDecimal("1999.00"),
      :currency_code    => "MXN",
      :memo => "Nomina",
      :cancel_url       => "http://lvh.me:3000/cancelled",
      :return_url       => "http://lvh.me:3000/subs/"+params[:id]
    ) do |response|
      # you may alternatively pass a PreapprovalRequest instance

      if response.success?
        puts "Preapproval key: #{response.preapproval_key}"

        # send the user to PayPal to give their approval
        # e.g. https://www.paypal.com/webscr?cmd=_ap-preapproval&preapprovalkey=abc
        payment.pak = response.preapproval_key
        payment.save
        redirect_to client.preapproval_url(response)
        
      else
        puts "#{response.ack_code}: #{response.error_message}"
        render json: response
      end

    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :last_name)
  end

  def after_sign_up_path_for(resource)
    dashboard_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title page_title
    content_for :title, page_title.to_s
  end
end

app/helpers/payment_schedules_helper.rb
module PaymentSchedulesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/dashboard/index.html.erb
<div class="dashboard-aside-menu">
  <a href="javascript:void(0)" class="button expand block">Nuevo pago</a>
  <div>
    <% @creditors.each do |c| %>
      <div>
        <span><% c.account %></span>
        <span><% c.amount %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if !flash.empty? %>
  <div class="flashes"> 
    <% flash.keys.each do |k| %> 
      <div class="flash <%= k %>">
        <%= flash[k] %>
        <a href="javascript:void(0)" data-close=""></a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fastjex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'fullpage.js/jquery.fullPage.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %> <%= action_name %>" data-controller="<%= controller.controller_name %>" data-action="<%= action_name %>">
<%= render "layouts/messages" %>
<header class="topbar">
  <h1 class="logo"></h1>
  <div class="absolute-right topbar-access-links">
    <% if user_signed_in? %>
      <%= link_to 'Salir', destroy_user_session_path, :method=>'delete' %>
    <% else %>
      <%= link_to 'Entrar', new_user_session_path %> · 
      <%= link_to 'Regístrate', new_user_registration_path %>
    <% end %>
  </div>
</header>
<%= yield %>

</body>
</html>

app/views/payment_schedules/_form.html.erb
<%= form_for(@payment_schedule) do |f| %>
  <% if @payment_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_schedule.errors.count, "error") %> prohibited this payment_schedule from being saved:</h2>

      <ul>
      <% @payment_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="field">
    <%= f.label :regularity %><br>
    <%= f.text_field :regularity %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_schedules/edit.html.erb
<h1>Editing Payment Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_schedule %> |
<%= link_to 'Back', payment_schedules_path %>

app/views/payment_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payment Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Regularity</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Amount</th>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_schedules.each do |payment_schedule| %>
      <tr>
        <td><%= payment_schedule.account %></td>
        <td><%= payment_schedule.regularity %></td>
        <td><%= payment_schedule.start_date %></td>
        <td><%= payment_schedule.end_date %></td>
        <td><%= payment_schedule.amount %></td>
        <td><%= payment_schedule.name %></td>
        <td><%= payment_schedule.user %></td>
        <td><%= link_to 'Show', payment_schedule %></td>
        <td><%= link_to 'Edit', edit_payment_schedule_path(payment_schedule) %></td>
        <td><%= link_to 'Destroy', payment_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment schedule', new_payment_schedule_path %>

app/views/payment_schedules/new.html.erb
<h1>New Payment Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_schedules_path %>

app/views/payment_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @payment_schedule.account %>
</p>

<p>
  <strong>Regularity:</strong>
  <%= @payment_schedule.regularity %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @payment_schedule.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @payment_schedule.end_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment_schedule.amount %>
</p>

<p>
  <strong>Name:</strong>
  <%= @payment_schedule.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @payment_schedule.user %>
</p>

<%= link_to 'Edit', edit_payment_schedule_path(@payment_schedule) %> |
<%= link_to 'Back', payment_schedules_path %>

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="field">
    <%= f.label :regularity %><br>
    <%= f.text_field :regularity %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payments</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Regularity</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Amount</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.account %></td>
        <td><%= payment.regularity %></td>
        <td><%= payment.start_date %></td>
        <td><%= payment.end_date %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.name %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @payment.account %>
</p>

<p>
  <strong>Regularity:</strong>
  <%= @payment.regularity %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @payment.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @payment.end_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Name:</strong>
  <%= @payment.name %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/payments/succeed.html.erb
<div class="bg-header"></div>
	<div class="wrap-xs">
	  <div class="logo x-centered l"></div>
	  <div class="panel text-center form-panel">
	  	<% if @response.payment_exec_status != "COMPLETED" %>
			<h3>Ocurrio un error, intenta de nuevo</h3>
		<%else%>
			<h3>El pago se añadio de forma correcta</h3>
		<%end%>
	  	<a href="/dashboard">Dashboard</a>
	  </div>
	</div>
</div>


<script>

</script>

app/views/welcome/index.html.erb
<div id="fullpage">
  <div class="section main">
    <div class="wrap-xs text-center">
      <h1>JEx</h1>
      <p>Automatización de pagos gone easy</p>
    </div>
  </div>
  <div class="section">
    <div class="wrap-xs text-left">
      <h1>Aquí te explicaría lo chingón de mi proyecto</h1>
      <p>Si tan solo lo fuera</p>
    </div>
  </div>
  <div class="section">
    <div class="wrap-xs text-right">
      <h1>Así que sólo llenaré espacio</h1>
      <p>Lorem ipsum dolor sit amet</p>
    </div>
  </div>
  <div class="section">
    <div class="wrap-xs text-right">
      <h1>Mucho espacio</h1>
      <p>Lorem ipsum dolor sit amet</p>
    </div>
  </div>
</div>